### PR TITLE
optimization for mobile viewing

### LINKED ISSUE #236: Frontend: Optimize for mobile viewing
There was a report on [English Wikipedia](https://en.wikipedia.org/wiki/Wikipedia_talk:Version_1.0_Editorial_Team/Index#Mobile_view) that some buttons look off when viewed on mobile. We should do a full pass of the frontend app and make sure it works on mobile. Using Bootstrap to begin with should help.

### PR DESCRIPTION
**Pull request by mahakporwal02**
@audiodude Sorry for late PR.
This fixed #236

### CODE REVIEW

**Comment by mahakporwal02** [comment]
wp1
local1

**Review by audiodude — CHANGES_REQUESTED** [review]
Just want to make sure, was this formatted with prettier? If you've installed pre-commit it should happen automatically.

**Comment by mahakporwal02** [comment]
@audiodude Sorry, earlier there was an issue in installation of pre-commit.
I have corrected it at once.

**Review by audiodude — APPROVED** [review]
Thanks!

**Pull request merged**
