### PR TITLE
Use Swagger UI as index of API website

### PR DESCRIPTION
**Pull request by audiodude**
This PR merges the changes from the `storybook` branch, which created a separate /v1/projects path for API calls. It additionally serves the Swagger UI from the root of the API website, with the swagger.yml file living at the top level of the project, but symlinked into the web module.

### CODE REVIEW

**Comment by audiodude** [comment]
The intention is to merge #131 first, and then merge this on top of that.

**Comment by kelson42** [comment]
@rgaudin Would you be able to make a brief review please?

**Comment by rgaudin** [comment]
OK could you please merge and rebase with #131 ?

**Comment by audiodude** [comment]
@rgaudin I didn't know how to do the rebase properly (was getting lots of conflicts) so I just merged #131 to master and then merged master here, then did a force update.

Let me know if this works.

**Comment by audiodude** [comment]
To be clear, I simply installed `swagger-ui-dist`, then copied its static assets to the web server module. I then updated the Flask server so that the root path (/) serves the swagger UI.

**Comment by kelson42** [comment]
@audiodude To rebase branch `storybook-swagger` on the top of `master`, do in branch `storybook-swagger`: `git rebase origin/master` or `git rebase master` if your local `master` is synced.

**Comment by kelson42** [comment]
@audiodude @rgaudin I'm not sure to 100% understand, but this is important that we don't have external code in our code repo. @rgaudin You have solved this stuff with the zimfarm.

**Comment by audiodude** [comment]
I've changed the spec to Open API 3.0.0 and removed the swagger-ui-dist directory, replaced with just a n index file that loads swagger-ui-dist from CDN.

PTAL, thanks!

**Comment by audiodude** [comment]
@rgaudin Thanks again for the review!

Thanks for the tip on validating the API spec. Also I've removed the zimfarm favicon....

**Pull request merged**
